name: switchfin
summary: switchfin
description: |
  third-party PC player for Jellyfin
version: "0.1.0"
grade: stable
icon: ../resources/icon/icon.png
base: core20
confinement: strict
license: Apache-2.0

apps:
  switchfin:
    command: usr/bin/Switchfin
    plugs:
      - desktop
      - wayland
      - x11
      - opengl
      - network

layout:
  /usr/lib/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/resources:
    bind: $SNAP/usr/resources

parts:
  libmpv:
    source: https://github.com/mpv-player/mpv/archive/v0.36.0.tar.gz
    source-type: tar
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --default-library=shared
      - -Dcplayer=false
      - -Dlibmpv=true
      - -Dtests=false
      - -Dplain-gl=enabled
      - -Dalsa=disabled
      - -Dlua=disabled
    stage-packages:
      - libdrm2
    prime:
      - -etc
      - -usr/bin
      - -usr/share
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
    after:
      - ffmpeg
      - libass

  ffmpeg:
    source: https://ffmpeg.org/releases/ffmpeg-5.1.3.tar.gz
    source-type: tar
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - --enable-shared
      - --disable-static
      - --disable-doc
      - --disable-programs
      - --disable-encoders
      - --disable-muxers
      - --enable-gpl
      - --enable-gnutls
      - --enable-encoder=png,libwebp
      - --enable-libdav1d
      - --enable-libfontconfig
      - --enable-libfreetype
      - --enable-libopus
      - --enable-librsvg
      - --enable-libwebp
    build-packages:
      - nasm
      - libfontconfig1-dev
      - libfreetype6-dev
      - libopus-dev
      - librsvg2-dev
      - libwebp-dev
      - libgnutls28-dev
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libopus0
      - librsvg2-2
      - libwebp6
      - libxv1
    after:
      - dav1d
    prime:
      - -etc
      - -usr/bin
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/share

  dav1d:
    plugin: meson
    source: https://code.videolan.org/videolan/dav1d.git
    source-tag: 1.2.1
    source-depth: 1
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --strip
      - -Denable_tools=false
      - -Denable_tests=false
    build-packages:
      - libxxhash-dev
    stage-packages:
      - libxxhash0
    prime:
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/share

  libass:
    source: https://github.com/libass/libass/releases/download/0.17.1/libass-0.17.1.tar.gz
    source-type: tar
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - --disable-static
    build-packages:
      - libfribidi-dev
      - libharfbuzz-dev
    stage-packages:
      - libfribidi0
      - libharfbuzz0b
    prime:
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/share

  switchfin:
    plugin: cmake
    source: ".."
    source-type: local
    cmake-parameters:
      - -DPLATFORM_DESKTOP=ON
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCUSTOM_RESOURCES_DIR=/usr
    build-environment:
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    build-packages:
      - g++
      - xorg-dev
      - libdbus-1-dev
      - libcurl4-gnutls-dev
    stage-packages:
      - libgl1-mesa-glx
      - libcurl3-gnutls
    after:
      - libmpv
    prime:
      - -etc
      - -usr/bin/fc-*
      - -usr/share
